### ISSUE TITLE
Desplegar pipeline multistream en staging y testear

### ISSUE THREAD

**Issue by pgallardor** [alercebroker/kubernetes_pipeline#74]
- [x] Sorting Hat
- [x] Previous Candidates
- [x] Lightcurve Step
- [x] Correction Step

**Comment by dirodriguezm** [comment]
El paso de lightcurve tiene un error al buscar la curva de luz en BD.

```
Traceback (most recent call last):
  File "/app/scripts/run_step.py", line 40, in <module>
    step_creator().start()
  File "/usr/local/lib/python3.9/site-packages/apf/core/step.py", line 372, in start
    result = self.execute(preprocessed_msg)
  File "/app/lightcurve_step/step.py", line 77, in execute
    self.clean_detections_from_db(detections_in_db)
  File "/app/lightcurve_step/step.py", line 102, in clean_detections_from_db
    for detection in detections:
TypeError: 'Pagination' object is not iterable
```

**Comment by dirodriguezm** [comment]
En correction hay un error que no se ha solucionado todavía

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/correction/_step/__init__.py", line 5, in run_step
    CorrectionStep.create_step().start()
  File "/usr/local/lib/python3.10/site-packages/apf/core/step.py", line 374, in start
    result = self._pre_produce(result)
  File "/usr/local/lib/python3.10/site-packages/apf/core/step.py", line 237, in _pre_produce
    message_to_produce = self.pre_produce(result)
  File "/app/correction/_step/step.py", line 52, in pre_produce
    non_detections = pd.DataFrame(result["non_detections"]).groupby("aid")
  File "/usr/local/lib/python3.10/site-packages/pandas/core/frame.py", line 8402, in groupby
    return DataFrameGroupBy(
  File "/usr/local/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 965, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/usr/local/lib/python3.10/site-packages/pandas/core/groupby/grouper.py", line 888, in get_grouper
    raise KeyError(gpr)
KeyError: 'aid'

```
